import Head from 'next/head'
import { FaChevronRight, FaFacebook, FaInstagram, FaLinkedin, FaTwitter} from "react-icons/fa";
import About from '../components/About'
import Experience from '../components/Experience'
//import Skills from '../components/Skills'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <div className={styles.navbar_container}>
        <p className={styles.myLogo}>
          <span className={styles.letterR}>R</span>
          <span className={styles.letterH}>h</span>
          <span className={styles.letterY}>y</span>
          <span className={styles.letterD}>d</span>
          <span className={styles.letterh}>h</span>
          <span className={styles.letterU}>u</span>
          <span className={styles.letterr}>r</span>
        </p>
          <div className={styles.nav_item_container}>
              <a href="#about" className={styles.nav_item} name="about"><span className={styles.numbers}>01.</span>About</a>
              <a href="#services" className={styles.nav_item} name="services"><span className={styles.numbers}>02.</span>Skills</a>
              <a href="#projects" className={styles.nav_item} name="projects"><span className={styles.numbers}>03.</span>Experience</a>
              <a href="#FAQ" className={styles.nav_item} name="FAQ"><span className={styles.numbers}>04.</span>Projects</a>
              <a href="#contacts" className={styles.nav_item} name="contacts"><span className={styles.numbers}>05.</span>Contact</a>
          </div>
      </div>

      <div className={styles.introSection}>
       <div className={styles.introSectionWrapper}>
         <p className={`${styles.greeting} ${styles.resetPadding} ${styles.addFontWeight}`}>Hi, my name is</p>
         <p className={styles.myName}>Ridwan Kolawole.</p>
         <p className={`${styles.slogan} ${styles.resetPadding}`}>I use technology to build for humans.</p>
         <p className={styles.greeting}>
           I'm a Frontend Software engineer with over 4 years of experience using different tools to build software platforms and applications providing solutions to 
           client's problems digitally.
        </p>
        <p className={styles.greeting}>
          I'm a programming enthusiast that loves being challenged while enjoying my journey towards making the world a betters place through my technological skills in addressing problems
          with both web and mobile softwares.
        </p>
        <a className={styles.navBtn}>Get in touch</a>
       </div>
      </div>

      <div className={styles.contentSection}>
        <About />
        <Experience />
        {/* <Skills /> */}
      </div>

      <div className={styles.contactWrapper}>
        <FaFacebook className={styles.linkIcons} />
        <FaInstagram className={styles.linkIcons} />
        <FaLinkedin className={styles.linkIcons} />
        <FaTwitter className={styles.linkIcons} />
        <div className={styles.verticalLine}></div>
      </div>
      <div className={styles.emailWrapper}>
        <p className={styles.emailText}>olaniyi.jibola152@gmail.com</p>
        <div className={styles.verticalLine}></div>
      </div>
    </div>
  )
}
